version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
      - ping_featurepeek:
          requires:
            - aws-ecr/build_and_push_image
jobs:
  ping_featurepeek:
    docker:
      - image: "circleci/node:12"
    steps:
      - run: bash <(curl -s https://peek.run/ci) -p ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}
